/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>

int main(void)
{
	uint32_t volatile *pRCCReg = (uint32_t*)0x40023830;
	uint32_t volatile *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t volatile *pPortDOutReg = (uint32_t*)0x40020C14;
	uint32_t volatile *pPortAModeReg = (uint32_t*)0x40020000;
	uint32_t volatile *pPortAInReg = (uint32_t*)0x40020010;

	//Enable the clock for GPOID , GPIOA peripherals in the AHB1ENR
	*pRCCReg |= (1 << 3);
	*pRCCReg |= (1 << 0);

	//Configuring PD12 as output
	*pPortDModeReg &= ~(3 << 24);
	//Make 24th bit position as 1 (SET)
	*pPortDModeReg |= (1 << 24);

	//Configure PA0 as input mode (GPIOA MODE REGISTER)
	*pPortAModeReg &= ~(3 << 0);

	while(1){
		//Read the pin status of the pin PA0 (GPIOA INPUT DATA REGISTER)
		uint8_t pinStatus = (uint8_t)(*pPortAInReg & 0x01);

		if(pinStatus){
			//Turn on the LED
			*pPortDOutReg |= (1 << 12);
		}else{
			//Turn off the LED
			*pPortDOutReg &= ~(1 << 12);
		}
	}
}
